### PR TITLE
Various updates to text and markdown.

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
I saw a few typos while reviewing for the [FSD](https://directory.fsf.org/wiki/Gammath_SPOT) and ended up making this PR.

- Fixed typos.
- Changed explicit numbering to implicit numbering.
- Rephrased line items into sentences.
- Placed backticks around code snippets and explicit file and directory names.
- Linked to sample.
- Other minor cleanups.

### CODE REVIEW

**Comment by salylgw** [comment]
Hi Michael,

Thanks for making this change. I'll resolve the conflicts and merge it into the baseline this week.

Cheers,
Salyl

**Comment by salylgw** [comment]
Hi Michael,

Looks great. Just merged.

Cheers,
Salyl

**Comment by salylgw** [comment]
Hi Michael,

I'm planning to add a contributors list file to this project. Are you okay if I add you to it? Please let me know.

Best regards,
Salyl

**Comment by TechnologyClassroom** [comment]
@salylgw Sure, thanks!

**Pull request merged**
